# Generated by Django 3.1.7 on 2022-11-05 15:31

from django.db import migrations, models
import django.views.generic.list


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_user_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPostsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(django.views.generic.list.ListView, models.Model),
        ),
    ]
