# Generated by Django 3.1.7 on 2022-11-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_allpostsview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
