# Generated by Django 4.1.1 on 2022-12-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('todo', 'todo'), ('canceled', 'canceled')], default='todo', max_length=25),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='time_spent',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='TimeClock',
        ),
    ]
