# Generated by Django 4.1.1 on 2022-12-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(default='Default', max_length=250),
            preserve_default=False,
        ),
    ]
