# Generated by Django 4.1.1 on 2022-12-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0002_alter_project_budget_dollars_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('canceled', 'canceled'), ('complete', 'complete')], default='todo', max_length=25),
        ),
    ]
