# Generated by Django 4.1.1 on 2022-12-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_alter_projecttask_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttask',
            name='time_spent',
        ),
        migrations.AddField(
            model_name='project',
            name='time_spent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('complete', 'complete'), ('canceled', 'canceled')], default='todo', max_length=25),
        ),
    ]
