# Generated by Django 4.1.1 on 2022-12-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_remove_projecttask_time_spent_project_time_spent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='time_spent',
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('canceled', 'canceled'), ('complete', 'complete')], default='todo', max_length=25),
        ),
        migrations.CreateModel(
            name='TimeClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elapsed_time', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.project')),
            ],
        ),
    ]
