# Generated by Django 4.1.1 on 2022-12-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_alter_projecttask_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='timemodel_set',
            new_name='time_models',
        ),
    ]
