# Generated by Django 4.1.1 on 2022-12-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0008_rename_timemodel_set_project_time_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timemodel',
            name='current_time',
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('todo', 'todo'), ('canceled', 'canceled')], default='todo', max_length=25),
        ),
    ]
