# Generated by Django 4.1.1 on 2022-12-09 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_remove_timemodel_current_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timemodel',
            name='project',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='track.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('canceled', 'canceled'), ('todo', 'todo')], default='todo', max_length=25),
        ),
    ]
