# Generated by Django 4.1.1 on 2022-12-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_timemodel_project_alter_projecttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('complete', 'complete'), ('todo', 'todo')], default='todo', max_length=25),
        ),
    ]
