# Generated by Django 4.1.1 on 2022-12-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_alter_projecttask_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invoice_status',
            field=models.CharField(choices=[('credit_memo', 'credit_memo'), ('pending', 'pending'), ('paid', 'paid')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('canceled', 'canceled'), ('todo', 'todo')], default='todo', max_length=25),
        ),
    ]
