# Generated by Django 4.1.1 on 2022-12-10 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_project_invoice_status_alter_projecttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='invoice_status',
            field=models.CharField(choices=[('pending', 'pending'), ('credit_memo', 'credit_memo'), ('paid', 'paid')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(choices=[('canceled', 'canceled'), ('complete', 'complete'), ('todo', 'todo')], default='todo', max_length=25),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.project')),
            ],
        ),
    ]
