# Generated by Django 3.1.7 on 2022-12-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_alter_project_invoice_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_address1',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_citystatezip',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='invoice_status',
            field=models.CharField(choices=[('paid', 'paid'), ('pending', 'pending'), ('credit_memo', 'credit_memo')], default='pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='projecttask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timeclock',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timemodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
